

namespace EMK.Save.BL.Models
{
    /// <summary>
    /// Carries the short-lived Plaid link_token generated by the API
    /// and returned to the React PWA to initialize Plaid Link.
    /// Not persisted — request/response transport only.
    /// </summary>
    public class PlaidLinkToken
    {
        [DisplayName("Link Token")]
        public string LinkToken { get; set; } = string.Empty;

        [DisplayName("Expiration")]
        public DateTime Expiration { get; set; }

        [DisplayName("Request ID")]
        public string RequestId { get; set; } = string.Empty;
    }

    /// <summary>
    /// Sent by the PWA after the user completes Plaid Link.
    /// The API exchanges the public_token for an access_token server-side.
    /// </summary>
    public class PlaidPublicTokenExchange
    {
        [DisplayName("Public Token")]
        public string PublicToken { get; set; } = string.Empty;

        [DisplayName("Institution ID")]
        public string InstitutionId { get; set; } = string.Empty;

        [DisplayName("Institution Name")]
        public string InstitutionName { get; set; } = string.Empty;

        [DisplayName("Institution Logo URL")]
        public string InstitutionLogoUrl { get; set; } = string.Empty;

        /// <summary>Account IDs the user selected in Plaid Link UI.</summary>
        [DisplayName("Selected Account IDs")]
        public List<string> SelectedAccountIds { get; set; } = new List<string>();
    }
}
