// <auto-generated />
using System;
using EMK.Save.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMK.Save.PL.Migrations
{
    [DbContext(typeof(SaveEntities))]
    [Migration("20260707173839_SaveDb")]
    partial class SaveDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RolloverAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudget_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b308c14-59f2-483e-a1c6-9cf5695a1055"),
                            CategoryId = new Guid("4802be14-6e75-4f32-9ef4-3219fb2d1381"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 1500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("1414712e-5ffe-46b0-9928-d47937766ccf"),
                            CategoryId = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 400m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("cef43024-460f-42ad-b2a1-8d2c8fe591be"),
                            CategoryId = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 200m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("d4fdf597-8fda-4def-8a46-b2f405fca028"),
                            CategoryId = new Guid("74dd7e95-eb7c-4032-ab14-80c624b4f7c3"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 250m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("ee753c14-52ac-477d-b056-f7b62befaa00"),
                            CategoryId = new Guid("273366f8-4856-4b80-aabd-0685e83c484c"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 100m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("eb7b5e5b-ace1-47db-b3bb-1274f0a6c6f2"),
                            CategoryId = new Guid("b65d18dd-d97a-460d-9d66-c5c1c8369757"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 150m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("1d488bb4-8c78-4e2c-a3c3-104c8d1bbcd8"),
                            CategoryId = new Guid("cd79f3e9-b67d-4a88-978f-6dc315b3b688"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("664a6f15-114f-4989-9115-7e7fd2f1adc9"),
                            CategoryId = new Guid("99763208-7007-4ced-947f-c87cc5a87ee8"),
                            Month = 7,
                            Notes = "Monthly salary",
                            PlannedAmount = 5000m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudgetCategory_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudgetCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4802be14-6e75-4f32-9ef4-3219fb2d1381"),
                            CategoryType = 1,
                            Color = "#2a78d6",
                            Icon = "ti-home",
                            IsActive = true,
                            Name = "Housing",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            CategoryType = 1,
                            Color = "#1baf7a",
                            Icon = "ti-shopping-cart",
                            IsActive = true,
                            Name = "Groceries",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            CategoryType = 1,
                            Color = "#eda100",
                            Icon = "ti-tools-kitchen",
                            IsActive = true,
                            Name = "Dining Out",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("74dd7e95-eb7c-4032-ab14-80c624b4f7c3"),
                            CategoryType = 1,
                            Color = "#4a3aa7",
                            Icon = "ti-car",
                            IsActive = true,
                            Name = "Transport",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("273366f8-4856-4b80-aabd-0685e83c484c"),
                            CategoryType = 1,
                            Color = "#e34948",
                            Icon = "ti-device-tv",
                            IsActive = true,
                            Name = "Entertainment",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("b65d18dd-d97a-460d-9d66-c5c1c8369757"),
                            CategoryType = 1,
                            Color = "#e87ba4",
                            Icon = "ti-heart",
                            IsActive = true,
                            Name = "Healthcare",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("cd79f3e9-b67d-4a88-978f-6dc315b3b688"),
                            CategoryType = 2,
                            Color = "#008300",
                            Icon = "ti-piggy-bank",
                            IsActive = true,
                            Name = "Savings",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("99763208-7007-4ced-947f-c87cc5a87ee8"),
                            CategoryType = 0,
                            Color = "#1baf7a",
                            Icon = "ti-wallet",
                            IsActive = true,
                            Name = "Income",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DayExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ProjectedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCashFlowEntry_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblCashFlowEntry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9264fdb-70e9-4058-a035-f55ce4889074"),
                            DayExpenses = 1500m,
                            DayIncome = 5000m,
                            EntryDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3500m,
                            RunningBalance = 3500m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("7e6c26bc-9b50-47a4-94a5-046b9374e63b"),
                            DayExpenses = 127m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3373m,
                            RunningBalance = 3373m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("9466fc40-06c7-4f1a-9dad-412a43116262"),
                            DayExpenses = 14m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3359m,
                            RunningBalance = 3359m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("14113ed4-1cff-4792-b8df-eb9398f10519"),
                            DayExpenses = 62m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3297m,
                            RunningBalance = 3297m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("0b7f4b18-acb3-4ab7-905c-e9492f848375"),
                            DayExpenses = 18m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 2800m,
                            RunningBalance = 3279m,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCategorySummary_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("tblCategorySummary", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f76f60e5-9c89-4f7f-a5bd-421c23e20d64"),
                            ActualAmount = 1500m,
                            CategoryId = new Guid("4802be14-6e75-4f32-9ef4-3219fb2d1381"),
                            PlannedAmount = 1500m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("808ef97f-b4c2-4f91-ac18-3a8ed618ad8a"),
                            ActualAmount = 380m,
                            CategoryId = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            PlannedAmount = 400m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 5
                        },
                        new
                        {
                            Id = new Guid("00814d89-e4ec-4483-adc5-1777f4d6b4b8"),
                            ActualAmount = 260m,
                            CategoryId = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            PlannedAmount = 200m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 8
                        },
                        new
                        {
                            Id = new Guid("7f51b9a8-a594-4635-87bb-272569a11d96"),
                            ActualAmount = 290m,
                            CategoryId = new Guid("74dd7e95-eb7c-4032-ab14-80c624b4f7c3"),
                            PlannedAmount = 250m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 6
                        },
                        new
                        {
                            Id = new Guid("6aac8402-bc73-4a75-8b2e-abf08600a24b"),
                            ActualAmount = 85m,
                            CategoryId = new Guid("273366f8-4856-4b80-aabd-0685e83c484c"),
                            PlannedAmount = 100m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 3
                        },
                        new
                        {
                            Id = new Guid("41dbcac4-5b17-4d48-a1dd-8ad82901d6dc"),
                            ActualAmount = 105m,
                            CategoryId = new Guid("b65d18dd-d97a-460d-9d66-c5c1c8369757"),
                            PlannedAmount = 150m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 4
                        },
                        new
                        {
                            Id = new Guid("64ed7a0a-5de8-47bb-8a40-300a8afea265"),
                            ActualAmount = 300m,
                            CategoryId = new Guid("cd79f3e9-b67d-4a88-978f-6dc315b3b688"),
                            PlannedAmount = 500m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("60190e01-32da-4a2e-89e7-0a17dfb6fba5"),
                            ActualAmount = 5000m,
                            CategoryId = new Guid("99763208-7007-4ced-947f-c87cc5a87ee8"),
                            PlannedAmount = 5000m,
                            SnapshotId = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OverBudgetCategoryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalBudgeted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblMonthlySnapshot_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblMonthlySnapshot", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("51f24e9f-da2c-44fb-bfa6-ed26fcef8fb1"),
                            Month = 5,
                            OverBudgetCategoryCount = 1,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SnapshotDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2650m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 42,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("0a2704d9-fd7a-40bd-82f9-66fd8bbd65f9"),
                            Month = 6,
                            OverBudgetCategoryCount = 2,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            SnapshotDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2920m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 38,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsPushEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LargeTransactionThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("NotifyMonthlySummary")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetOverage")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetWarning")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnLargeTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnNewTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnSyncError")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWeeklySummary")
                        .HasColumnType("bit");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<TimeOnly>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblNotificationPreference_Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblNotificationPreference_UserId");

                    b.ToTable("tblNotificationPreference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("983f79ed-60f6-44b4-858b-74aec12fc14b"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 100m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = true,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = true,
                            NotifyOnLargeTransaction = true,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        },
                        new
                        {
                            Id = new Guid("41f9fa79-4380-4e3c-b99f-ca087846c6fe"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 200m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = false,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = false,
                            NotifyOnLargeTransaction = false,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("5ddab21a-0717-4cfa-a40c-ea59da059d0e")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AccountSubtype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateLinked")
                        .HasColumnType("datetime");

                    b.Property<string>("InstitutionLogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlaidAccount_Id");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlaidAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Checking",
                            AccountSubtype = "checking",
                            AccountType = "depository",
                            AvailableBalance = 3150.00m,
                            CurrentBalance = 3200.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "1234",
                            PlaidAccountId = "demo_chk_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        },
                        new
                        {
                            Id = new Guid("38502936-10b3-476f-85cb-11659e6a076b"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Savings",
                            AccountSubtype = "savings",
                            AccountType = "depository",
                            AvailableBalance = 8500.00m,
                            CurrentBalance = 8500.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "5678",
                            PlaidAccountId = "demo_sav_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPushNotification_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPushNotification", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("56bb51db-c194-40ec-96cf-56da2e7bc3cf"),
                            ActionUrl = "/budget",
                            Amount = 60m,
                            Body = "You've exceeded your Dining Out budget by $60.",
                            CategoryId = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 1,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Status = 1,
                            Title = "Dining Out over budget!",
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        },
                        new
                        {
                            Id = new Guid("6b511dfd-878e-4df9-b5f9-d1ac6d1deab0"),
                            ActionUrl = "/transactions",
                            Amount = 7m,
                            Body = "A $7.00 charge at Starbucks is pending review.",
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 0,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Status = 1,
                            Title = "New transaction: Starbucks",
                            TransactionId = new Guid("8fd372eb-c8ce-4df0-8dcb-5107c408a00c"),
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        },
                        new
                        {
                            Id = new Guid("e4dd7062-3df5-4b8c-9874-293db0365446"),
                            ActionUrl = "/budget",
                            Amount = 200m,
                            Body = "You've used 80% of your Transport budget.",
                            CategoryId = new Guid("74dd7e95-eb7c-4032-ab14-80c624b4f7c3"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = true,
                            NotificationType = 2,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Status = 1,
                            Title = "Transport at 80%",
                            UserId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblSharedBudget_Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("UX_tblSharedBudget_InviteCode");

                    b.ToTable("tblSharedBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shared household budget",
                            InviteCode = "XEESFJ",
                            IsActive = true,
                            MaxMembers = 10,
                            Name = "Demo Family Budget",
                            OwnerId = new Guid("f3a19404-554e-4297-a043-189d327532c6")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("InsightType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblTrackingInsight_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblTrackingInsight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2457fd5-4f6d-46e2-b0a5-8ac1a71fdeaf"),
                            Amount = 60m,
                            CategoryId = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            ChangePercent = 30.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 0,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You've spent $60 more than planned on dining this month.",
                            Month = 7,
                            Severity = 2,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Title = "Dining Out over budget",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("9ac2c910-6758-4de3-a82c-c81e71773e71"),
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 7,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You have 2 transactions that haven't been assigned to a budget category.",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Title = "2 unassigned transactions",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("5ec45efa-9211-4a7d-b1cb-cf455080fab5"),
                            CategoryId = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            ChangePercent = -5.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 1,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You're spending less on groceries than last month — great job!",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            Title = "Groceries on track",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PlaidAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaidCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidSubcategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("tblBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTransaction_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaidAccountId");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblTransaction_PlaidTransactionId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("tblBudgetId");

                    b.ToTable("tblTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6af45b9d-c431-4fd4-aa6f-9c9568540085"),
                            Amount = -1500m,
                            CategoryId = new Guid("4802be14-6e75-4f32-9ef4-3219fb2d1381"),
                            Description = "Monthly rent",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Rent Payment",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Payment",
                            PlaidSubcategory = "Rent",
                            PlaidTransactionId = "txn_001",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1dd49adb-9111-4143-9ddc-66be00ec2c89"),
                            Amount = -127m,
                            CategoryId = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Whole Foods",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_002",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cefe3de1-eaef-4e77-9a20-d53447c1df74"),
                            Amount = -14m,
                            CategoryId = new Guid("088af96a-f35e-4ecf-a7bb-dcfe18e4491f"),
                            Description = "Lunch",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Chipotle",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Restaurants",
                            PlaidTransactionId = "txn_003",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("899a0a35-5edf-45d0-8830-49a5145f16ec"),
                            Amount = -62m,
                            CategoryId = new Guid("74dd7e95-eb7c-4032-ab14-80c624b4f7c3"),
                            Description = "Fuel",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Shell Gas Station",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Travel",
                            PlaidSubcategory = "Gas Stations",
                            PlaidTransactionId = "txn_004",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3c06d38a-68f6-4309-9f7a-031eb6c0290b"),
                            Amount = -18m,
                            CategoryId = new Guid("273366f8-4856-4b80-aabd-0685e83c484c"),
                            Description = "Streaming sub",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Netflix",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Service",
                            PlaidSubcategory = "Subscription",
                            PlaidTransactionId = "txn_005",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2cf7c40b-90c4-4bd0-8bba-4ad5e4ac7260"),
                            Amount = 5000m,
                            CategoryId = new Guid("99763208-7007-4ced-947f-c87cc5a87ee8"),
                            Description = "Payroll",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Employer Direct Dep",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Payroll",
                            PlaidSubcategory = "Payroll",
                            PlaidTransactionId = "txn_006",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4d29c646-7305-45e7-bad4-fdfadb90bc60"),
                            Amount = -89m,
                            CategoryId = new Guid("ff9a4543-7ce6-4dca-b999-df4b089369b2"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Trader Joe's",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_007",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bd4b9933-4ab3-4e43-bdb9-31a998689b80"),
                            Amount = -43m,
                            Description = "Online purchase",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Amazon",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Shopping",
                            PlaidSubcategory = "Online",
                            PlaidTransactionId = "txn_008",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8fd372eb-c8ce-4df0-8dcb-5107c408a00c"),
                            Amount = -7m,
                            Description = "Coffee",
                            IsExcluded = false,
                            IsPending = true,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Starbucks",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Coffee Shop",
                            PlaidTransactionId = "txn_009",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b952159c-ca31-436b-b8e0-643181606487"),
                            Amount = -38m,
                            CategoryId = new Guid("b65d18dd-d97a-460d-9d66-c5c1c8369757"),
                            Description = "Pharmacy",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "CVS Pharmacy",
                            Notes = "",
                            PlaidAccountId = new Guid("1f749ecc-0210-4cd6-8ade-a6f5151045aa"),
                            PlaidCategory = "Medical",
                            PlaidSubcategory = "Pharmacies",
                            PlaidTransactionId = "txn_010",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TransactionDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BudgetRole")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3a19404-554e-4297-a043-189d327532c6"),
                            BudgetRole = 0,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@emksave.com",
                            FirstName = "Alex",
                            LastName = "Demo",
                            Password = "210000.r27gfn+F0KYK/X3FURCZrg==.q56PYreQxT4JsNtHBdOB4LCfEZbJARPmH193+wdBV6M=",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TimeZone = "America/Chicago",
                            UserId = "owner"
                        },
                        new
                        {
                            Id = new Guid("5ddab21a-0717-4cfa-a40c-ea59da059d0e"),
                            BudgetRole = 1,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamie@emksave.com",
                            FirstName = "Jamie",
                            LastName = "Smith",
                            Password = "210000.X5yQzVjG+AyJg8dN1S88fw==.I/2k8kA+8VFRva9LwLxACnH0/ud3YIDynODIKqYQobY=",
                            SharedBudgetId = new Guid("e525f430-337e-4147-ae42-07fd8fdce182"),
                            TimeZone = "America/Chicago",
                            UserId = "member"
                        },
                        new
                        {
                            Id = new Guid("1cb9f7cf-89cd-4577-b2db-14708eedac8a"),
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taylor@emksave.com",
                            FirstName = "Taylor",
                            LastName = "New",
                            Password = "210000.bSJrhIp7rjY84FV7PVRhYQ==.47xyRn9TSKbqrYZODyfwsKyx2P05DFidHEaOzN32H+0=",
                            TimeZone = "America/Chicago",
                            UserId = "solo"
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Budgets")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudgetCategory_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCashFlowEntry_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblMonthlySnapshot", "Snapshot")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_SnapshotId");

                    b.Navigation("Category");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMonthlySnapshot_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("EMK.Save.PL.Entities.tblNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblNotificationPreference_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_UserId");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("PushNotifications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblPushNotification_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PushNotifications")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblTransaction", "Transaction")
                        .WithMany("PushNotifications")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblPushNotification_TransactionId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PushNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_UserId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblTrackingInsight_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTrackingInsight_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblTransaction_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblPlaidAccount", "PlaidAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("PlaidAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_PlaidAccountId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany()
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblBudget", null)
                        .WithMany("Transactions")
                        .HasForeignKey("tblBudgetId");

                    b.Navigation("Category");

                    b.Navigation("PlaidAccount");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Members")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblUser_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("CategorySummaries");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Navigation("CategorySummaries");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Budgets");

                    b.Navigation("CashFlowEntries");

                    b.Navigation("Members");

                    b.Navigation("MonthlySnapshots");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Navigation("PushNotifications");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Navigation("NotificationPreference");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
