// <auto-generated />
using System;
using EMK.Save.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMK.Save.PL.Migrations
{
    [DbContext(typeof(SaveEntities))]
    [Migration("20260707185259_SaveDb")]
    partial class SaveDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RolloverAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudget_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8236e33e-8659-45df-864f-2df47b429bb1"),
                            CategoryId = new Guid("f213e9aa-454f-4d45-9c7a-45f81fb6e5bd"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 1500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("c8ac551e-1242-4f12-bc94-9270cec1089d"),
                            CategoryId = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 400m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f0ea80d2-2d92-4e5a-9e3c-d014fcf57f56"),
                            CategoryId = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 200m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("20d8135a-7f35-4759-97d0-9d81f389ce05"),
                            CategoryId = new Guid("a330c6ee-742f-474a-86bc-9a3435f4404d"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 250m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("182199b0-9047-4c5f-993f-f7797ff05ac0"),
                            CategoryId = new Guid("18df092b-ac09-42e4-9cfc-63d94a947ceb"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 100m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("10610c70-55e9-408d-9d56-bdc11cf04db6"),
                            CategoryId = new Guid("a85f43a1-9796-4d2e-b722-5eaa6fedca0c"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 150m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fad8e459-770d-4abe-9d46-c2fa24802fbf"),
                            CategoryId = new Guid("2e07d55a-15f5-4b6c-9d60-6818f3e3f93f"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("9683508f-f172-4eb0-a9fa-4fc32419ac27"),
                            CategoryId = new Guid("16154f06-48c2-47c3-8aee-728a1bbfd358"),
                            Month = 7,
                            Notes = "Monthly salary",
                            PlannedAmount = 5000m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudgetCategory_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudgetCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f213e9aa-454f-4d45-9c7a-45f81fb6e5bd"),
                            CategoryType = 1,
                            Color = "#2a78d6",
                            Icon = "ti-home",
                            IsActive = true,
                            Name = "Housing",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            CategoryType = 1,
                            Color = "#1baf7a",
                            Icon = "ti-shopping-cart",
                            IsActive = true,
                            Name = "Groceries",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            CategoryType = 1,
                            Color = "#eda100",
                            Icon = "ti-tools-kitchen",
                            IsActive = true,
                            Name = "Dining Out",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a330c6ee-742f-474a-86bc-9a3435f4404d"),
                            CategoryType = 1,
                            Color = "#4a3aa7",
                            Icon = "ti-car",
                            IsActive = true,
                            Name = "Transport",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("18df092b-ac09-42e4-9cfc-63d94a947ceb"),
                            CategoryType = 1,
                            Color = "#e34948",
                            Icon = "ti-device-tv",
                            IsActive = true,
                            Name = "Entertainment",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("a85f43a1-9796-4d2e-b722-5eaa6fedca0c"),
                            CategoryType = 1,
                            Color = "#e87ba4",
                            Icon = "ti-heart",
                            IsActive = true,
                            Name = "Healthcare",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("2e07d55a-15f5-4b6c-9d60-6818f3e3f93f"),
                            CategoryType = 2,
                            Color = "#008300",
                            Icon = "ti-piggy-bank",
                            IsActive = true,
                            Name = "Savings",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("16154f06-48c2-47c3-8aee-728a1bbfd358"),
                            CategoryType = 0,
                            Color = "#1baf7a",
                            Icon = "ti-wallet",
                            IsActive = true,
                            Name = "Income",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DayExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ProjectedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCashFlowEntry_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblCashFlowEntry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("97e7607c-5198-4021-ab72-f35ceaf2625e"),
                            DayExpenses = 1500m,
                            DayIncome = 5000m,
                            EntryDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3500m,
                            RunningBalance = 3500m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("8b50f359-bc80-4dfb-9614-2c2e4c7bcaa7"),
                            DayExpenses = 127m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3373m,
                            RunningBalance = 3373m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("94c10ce3-1d3f-4bef-89a2-570f55f94e0d"),
                            DayExpenses = 14m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3359m,
                            RunningBalance = 3359m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("fb17517b-48b1-440a-b0d2-34bfbb169187"),
                            DayExpenses = 62m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3297m,
                            RunningBalance = 3297m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("33dd9864-1b71-48d8-a358-7bdfc1d0ea9c"),
                            DayExpenses = 18m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 2800m,
                            RunningBalance = 3279m,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCategorySummary_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("tblCategorySummary", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8978cb6a-6e56-4a46-aa77-fcd440bafbaf"),
                            ActualAmount = 1500m,
                            CategoryId = new Guid("f213e9aa-454f-4d45-9c7a-45f81fb6e5bd"),
                            PlannedAmount = 1500m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("efd17d60-c19f-403b-aa31-82c81d9a1459"),
                            ActualAmount = 380m,
                            CategoryId = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            PlannedAmount = 400m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 5
                        },
                        new
                        {
                            Id = new Guid("37e2ac2e-5ae2-4764-81a5-35cc14322957"),
                            ActualAmount = 260m,
                            CategoryId = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            PlannedAmount = 200m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 8
                        },
                        new
                        {
                            Id = new Guid("a79b401d-a9f8-40a4-b91d-20d807ab0632"),
                            ActualAmount = 290m,
                            CategoryId = new Guid("a330c6ee-742f-474a-86bc-9a3435f4404d"),
                            PlannedAmount = 250m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 6
                        },
                        new
                        {
                            Id = new Guid("5f165f3a-02dc-4bdd-a804-d5b85cf26c1a"),
                            ActualAmount = 85m,
                            CategoryId = new Guid("18df092b-ac09-42e4-9cfc-63d94a947ceb"),
                            PlannedAmount = 100m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 3
                        },
                        new
                        {
                            Id = new Guid("f43e9309-b14a-4135-9a8e-8530aea6c596"),
                            ActualAmount = 105m,
                            CategoryId = new Guid("a85f43a1-9796-4d2e-b722-5eaa6fedca0c"),
                            PlannedAmount = 150m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 4
                        },
                        new
                        {
                            Id = new Guid("c8592abb-e307-4d2c-b069-1410cf07623b"),
                            ActualAmount = 300m,
                            CategoryId = new Guid("2e07d55a-15f5-4b6c-9d60-6818f3e3f93f"),
                            PlannedAmount = 500m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("deba07d3-a38a-484f-81ec-36d323569c60"),
                            ActualAmount = 5000m,
                            CategoryId = new Guid("16154f06-48c2-47c3-8aee-728a1bbfd358"),
                            PlannedAmount = 5000m,
                            SnapshotId = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OverBudgetCategoryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalBudgeted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblMonthlySnapshot_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblMonthlySnapshot", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("81d4cb8c-424c-4d6a-9a85-c5f5c6a85875"),
                            Month = 5,
                            OverBudgetCategoryCount = 1,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SnapshotDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2650m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 42,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("9f6bdc8d-ec49-4621-aefa-c2a94662097b"),
                            Month = 6,
                            OverBudgetCategoryCount = 2,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            SnapshotDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2920m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 38,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsPushEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LargeTransactionThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("NotifyMonthlySummary")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetOverage")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetWarning")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnLargeTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnNewTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnSyncError")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWeeklySummary")
                        .HasColumnType("bit");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<TimeOnly>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblNotificationPreference_Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblNotificationPreference_UserId");

                    b.ToTable("tblNotificationPreference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("12cddeeb-9452-4312-9d86-a9599bd956b5"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 100m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = true,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = true,
                            NotifyOnLargeTransaction = true,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        },
                        new
                        {
                            Id = new Guid("422a5432-edd8-4ff4-a609-3c4f53d47a0f"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 200m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = false,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = false,
                            NotifyOnLargeTransaction = false,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("2addd71c-50c8-4910-8934-587dfddaf4e0")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AccountSubtype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateLinked")
                        .HasColumnType("datetime");

                    b.Property<string>("InstitutionLogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SyncCursor")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlaidAccount_Id");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlaidAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Checking",
                            AccountSubtype = "checking",
                            AccountType = "depository",
                            AvailableBalance = 3150.00m,
                            CurrentBalance = 3200.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "1234",
                            PlaidAccountId = "demo_chk_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        },
                        new
                        {
                            Id = new Guid("aa167159-7f7c-46e9-9d42-333959be8357"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Savings",
                            AccountSubtype = "savings",
                            AccountType = "depository",
                            AvailableBalance = 8500.00m,
                            CurrentBalance = 8500.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "5678",
                            PlaidAccountId = "demo_sav_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPushNotification_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPushNotification", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8630244-e86f-4f1b-9285-ed07a0d79e1b"),
                            ActionUrl = "/budget",
                            Amount = 60m,
                            Body = "You've exceeded your Dining Out budget by $60.",
                            CategoryId = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 1,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Status = 1,
                            Title = "Dining Out over budget!",
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        },
                        new
                        {
                            Id = new Guid("203b2b4d-c5ba-489e-8fb1-2c3127bdcf38"),
                            ActionUrl = "/transactions",
                            Amount = 7m,
                            Body = "A $7.00 charge at Starbucks is pending review.",
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 0,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Status = 1,
                            Title = "New transaction: Starbucks",
                            TransactionId = new Guid("69b27686-647a-4d48-901d-a92dd0371035"),
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        },
                        new
                        {
                            Id = new Guid("c4e6a911-fe26-4ab4-ad5d-00224602a66a"),
                            ActionUrl = "/budget",
                            Amount = 200m,
                            Body = "You've used 80% of your Transport budget.",
                            CategoryId = new Guid("a330c6ee-742f-474a-86bc-9a3435f4404d"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = true,
                            NotificationType = 2,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Status = 1,
                            Title = "Transport at 80%",
                            UserId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblSharedBudget_Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("UX_tblSharedBudget_InviteCode");

                    b.ToTable("tblSharedBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shared household budget",
                            InviteCode = "XEESFJ",
                            IsActive = true,
                            MaxMembers = 10,
                            Name = "Demo Family Budget",
                            OwnerId = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("InsightType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblTrackingInsight_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblTrackingInsight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb9e4f08-48ec-40c5-9b03-202d559bb4eb"),
                            Amount = 60m,
                            CategoryId = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            ChangePercent = 30.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 0,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You've spent $60 more than planned on dining this month.",
                            Month = 7,
                            Severity = 2,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Title = "Dining Out over budget",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("df23a5f8-6804-4212-9407-24a014791a74"),
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 7,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You have 2 transactions that haven't been assigned to a budget category.",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Title = "2 unassigned transactions",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("24cb8fcd-69b0-4f6c-b8f7-d5998acf8879"),
                            CategoryId = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            ChangePercent = -5.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 1,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You're spending less on groceries than last month — great job!",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            Title = "Groceries on track",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PlaidAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaidCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidSubcategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("tblBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTransaction_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaidAccountId");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblTransaction_PlaidTransactionId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("tblBudgetId");

                    b.ToTable("tblTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d29a7a52-876c-46fd-8541-e10bd4173bdf"),
                            Amount = -1500m,
                            CategoryId = new Guid("f213e9aa-454f-4d45-9c7a-45f81fb6e5bd"),
                            Description = "Monthly rent",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Rent Payment",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Payment",
                            PlaidSubcategory = "Rent",
                            PlaidTransactionId = "txn_001",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("91075ad3-670f-48a8-afb3-38924167ca9b"),
                            Amount = -127m,
                            CategoryId = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Whole Foods",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_002",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("66d6ff4f-81a7-4b29-b20a-bb8e931dd6ba"),
                            Amount = -14m,
                            CategoryId = new Guid("28d938ae-5d46-4ebe-bd6e-1cfe711e7886"),
                            Description = "Lunch",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Chipotle",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Restaurants",
                            PlaidTransactionId = "txn_003",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0bff46a3-5308-419e-b2ea-45dab1ae635b"),
                            Amount = -62m,
                            CategoryId = new Guid("a330c6ee-742f-474a-86bc-9a3435f4404d"),
                            Description = "Fuel",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Shell Gas Station",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Travel",
                            PlaidSubcategory = "Gas Stations",
                            PlaidTransactionId = "txn_004",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6233a16e-a489-4259-a25e-680a1284d1ed"),
                            Amount = -18m,
                            CategoryId = new Guid("18df092b-ac09-42e4-9cfc-63d94a947ceb"),
                            Description = "Streaming sub",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Netflix",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Service",
                            PlaidSubcategory = "Subscription",
                            PlaidTransactionId = "txn_005",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bce65089-5c9c-49cd-9a0e-e4c057d6f5d2"),
                            Amount = 5000m,
                            CategoryId = new Guid("16154f06-48c2-47c3-8aee-728a1bbfd358"),
                            Description = "Payroll",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Employer Direct Dep",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Payroll",
                            PlaidSubcategory = "Payroll",
                            PlaidTransactionId = "txn_006",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d7bbe1ac-5629-427e-8fec-389539efb37f"),
                            Amount = -89m,
                            CategoryId = new Guid("865d387b-a568-42d2-94f0-ce8abcf0af83"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Trader Joe's",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_007",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("da683557-8fa7-4757-bcd2-96caa2f404f4"),
                            Amount = -43m,
                            Description = "Online purchase",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Amazon",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Shopping",
                            PlaidSubcategory = "Online",
                            PlaidTransactionId = "txn_008",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("69b27686-647a-4d48-901d-a92dd0371035"),
                            Amount = -7m,
                            Description = "Coffee",
                            IsExcluded = false,
                            IsPending = true,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Starbucks",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Coffee Shop",
                            PlaidTransactionId = "txn_009",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("94804a3e-047d-4e0a-9666-910fb7d48344"),
                            Amount = -38m,
                            CategoryId = new Guid("a85f43a1-9796-4d2e-b722-5eaa6fedca0c"),
                            Description = "Pharmacy",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "CVS Pharmacy",
                            Notes = "",
                            PlaidAccountId = new Guid("6c6eee68-42e1-4175-8bb9-db17d1678823"),
                            PlaidCategory = "Medical",
                            PlaidSubcategory = "Pharmacies",
                            PlaidTransactionId = "txn_010",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TransactionDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BudgetRole")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f9f6c88-5c09-41ff-8b09-0ee67426fd15"),
                            BudgetRole = 0,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@emksave.com",
                            FirstName = "Alex",
                            LastName = "Demo",
                            Password = "210000.KQQBHUCITNCsf7vHNITa/g==.ipIC718UjA+o5oGnWMV47cOxqeAf2pd/Tekj3A2iJxE=",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TimeZone = "America/Chicago",
                            UserId = "owner"
                        },
                        new
                        {
                            Id = new Guid("2addd71c-50c8-4910-8934-587dfddaf4e0"),
                            BudgetRole = 1,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamie@emksave.com",
                            FirstName = "Jamie",
                            LastName = "Smith",
                            Password = "210000.PVOSX26R03MJMAT79eVt+w==.G2w9U1/DNw88fBiKKGgC3vif8oVaTDD/Lsa+g+JLlOc=",
                            SharedBudgetId = new Guid("41c394db-a679-405e-995f-b48ed42dab0c"),
                            TimeZone = "America/Chicago",
                            UserId = "member"
                        },
                        new
                        {
                            Id = new Guid("36a2d704-30af-484d-b73c-bfbb60e5e4fa"),
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taylor@emksave.com",
                            FirstName = "Taylor",
                            LastName = "New",
                            Password = "210000.Emgqctwvtp+1ZEtOw0L20g==.dJfRRDjOvcbwSl5/O078gSiNVmdl/u9/I2dKU30yrDE=",
                            TimeZone = "America/Chicago",
                            UserId = "solo"
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Budgets")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudgetCategory_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCashFlowEntry_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblMonthlySnapshot", "Snapshot")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_SnapshotId");

                    b.Navigation("Category");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMonthlySnapshot_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("EMK.Save.PL.Entities.tblNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblNotificationPreference_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_UserId");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("PushNotifications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblPushNotification_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PushNotifications")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblTransaction", "Transaction")
                        .WithMany("PushNotifications")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblPushNotification_TransactionId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PushNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_UserId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblTrackingInsight_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTrackingInsight_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_tblTransaction_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblPlaidAccount", "PlaidAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("PlaidAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_PlaidAccountId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany()
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblBudget", null)
                        .WithMany("Transactions")
                        .HasForeignKey("tblBudgetId");

                    b.Navigation("Category");

                    b.Navigation("PlaidAccount");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Members")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblUser_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("CategorySummaries");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Navigation("CategorySummaries");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Budgets");

                    b.Navigation("CashFlowEntries");

                    b.Navigation("Members");

                    b.Navigation("MonthlySnapshots");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Navigation("PushNotifications");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Navigation("NotificationPreference");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
