// <auto-generated />
using System;
using EMK.Save.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMK.Save.PL.Migrations
{
    [DbContext(typeof(SaveEntities))]
    partial class SaveEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RolloverAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudget_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f7f6894-ad6e-438d-bfd8-1366e7ea15a5"),
                            CategoryId = new Guid("ed9cb15e-29af-4e5a-bca3-e7a136517fb3"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 1500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("dc893dba-5026-4716-9bcb-f73ef44b4bdf"),
                            CategoryId = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 400m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("5d5a9776-a0d2-43b3-8e0e-0402971596e0"),
                            CategoryId = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 200m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("8f80773d-0e2b-4b72-bb6b-4055de1e2123"),
                            CategoryId = new Guid("79be1811-cf0f-428f-9f9c-31f0194c47ac"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 250m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("427c8836-123d-42e4-b0c1-815fc1b45522"),
                            CategoryId = new Guid("7b0e162c-cd9f-4540-b9e1-9ff5a18e18ad"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 100m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("15325532-a32a-46e8-8269-6def7847cea5"),
                            CategoryId = new Guid("94b0f9e0-87cd-4146-af66-add240f76988"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 150m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("8f6b8e11-0cf3-43ab-8c3b-a71afe4e81fc"),
                            CategoryId = new Guid("099994e2-6406-4d89-ba5c-7838a979a775"),
                            Month = 7,
                            Notes = "",
                            PlannedAmount = 500m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("f3b6f565-9cdd-407e-a750-63c14598cf31"),
                            CategoryId = new Guid("30ace2f8-7ae2-4ecb-afb2-046865a905a6"),
                            Month = 7,
                            Notes = "Monthly salary",
                            PlannedAmount = 5000m,
                            RolloverAmount = 0m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblBudgetCategory_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblBudgetCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed9cb15e-29af-4e5a-bca3-e7a136517fb3"),
                            CategoryType = 1,
                            Color = "#2a78d6",
                            Icon = "ti-home",
                            IsActive = true,
                            Name = "Housing",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            CategoryType = 1,
                            Color = "#1baf7a",
                            Icon = "ti-shopping-cart",
                            IsActive = true,
                            Name = "Groceries",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            CategoryType = 1,
                            Color = "#eda100",
                            Icon = "ti-tools-kitchen",
                            IsActive = true,
                            Name = "Dining Out",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("79be1811-cf0f-428f-9f9c-31f0194c47ac"),
                            CategoryType = 1,
                            Color = "#4a3aa7",
                            Icon = "ti-car",
                            IsActive = true,
                            Name = "Transport",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("7b0e162c-cd9f-4540-b9e1-9ff5a18e18ad"),
                            CategoryType = 1,
                            Color = "#e34948",
                            Icon = "ti-device-tv",
                            IsActive = true,
                            Name = "Entertainment",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("94b0f9e0-87cd-4146-af66-add240f76988"),
                            CategoryType = 1,
                            Color = "#e87ba4",
                            Icon = "ti-heart",
                            IsActive = true,
                            Name = "Healthcare",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("099994e2-6406-4d89-ba5c-7838a979a775"),
                            CategoryType = 2,
                            Color = "#008300",
                            Icon = "ti-piggy-bank",
                            IsActive = true,
                            Name = "Savings",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("30ace2f8-7ae2-4ecb-afb2-046865a905a6"),
                            CategoryType = 0,
                            Color = "#1baf7a",
                            Icon = "ti-wallet",
                            IsActive = true,
                            Name = "Income",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DayExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ProjectedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RunningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCashFlowEntry_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblCashFlowEntry", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("966265d0-e59d-470b-92fe-9b3ed1ef43c3"),
                            DayExpenses = 1500m,
                            DayIncome = 5000m,
                            EntryDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3500m,
                            RunningBalance = 3500m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("ec6e5661-f6d3-49de-815c-ca5569336095"),
                            DayExpenses = 127m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3373m,
                            RunningBalance = 3373m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("0de5086d-6fc8-4508-a55c-7928761f34f6"),
                            DayExpenses = 14m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3359m,
                            RunningBalance = 3359m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("07b18098-d525-4cde-ae15-3e8d62159166"),
                            DayExpenses = 62m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 3297m,
                            RunningBalance = 3297m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("2ce7c3a8-bcba-4088-aae0-b409e31d55f0"),
                            DayExpenses = 18m,
                            DayIncome = 0m,
                            EntryDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectedBalance = 2800m,
                            RunningBalance = 3279m,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblCategorySummary_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("tblCategorySummary", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bf540ea-94d7-41f9-a623-6949354ba864"),
                            ActualAmount = 1500m,
                            CategoryId = new Guid("ed9cb15e-29af-4e5a-bca3-e7a136517fb3"),
                            PlannedAmount = 1500m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 1
                        },
                        new
                        {
                            Id = new Guid("fc4695fc-da19-4000-b6c5-5385e3712321"),
                            ActualAmount = 380m,
                            CategoryId = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            PlannedAmount = 400m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 5
                        },
                        new
                        {
                            Id = new Guid("4347ce9e-9573-4cdd-a866-e42fc1869653"),
                            ActualAmount = 260m,
                            CategoryId = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            PlannedAmount = 200m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 8
                        },
                        new
                        {
                            Id = new Guid("708d4016-e9ae-4da1-a503-4dffd6678237"),
                            ActualAmount = 290m,
                            CategoryId = new Guid("79be1811-cf0f-428f-9f9c-31f0194c47ac"),
                            PlannedAmount = 250m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 6
                        },
                        new
                        {
                            Id = new Guid("fd3b4512-f342-4222-acfe-f30d57e71b9c"),
                            ActualAmount = 85m,
                            CategoryId = new Guid("7b0e162c-cd9f-4540-b9e1-9ff5a18e18ad"),
                            PlannedAmount = 100m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 3
                        },
                        new
                        {
                            Id = new Guid("ea90d390-1366-459d-bfbc-d2caedce4854"),
                            ActualAmount = 105m,
                            CategoryId = new Guid("94b0f9e0-87cd-4146-af66-add240f76988"),
                            PlannedAmount = 150m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 4
                        },
                        new
                        {
                            Id = new Guid("7f8e0721-8885-40b9-9101-a21baee493b3"),
                            ActualAmount = 300m,
                            CategoryId = new Guid("099994e2-6406-4d89-ba5c-7838a979a775"),
                            PlannedAmount = 500m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 2
                        },
                        new
                        {
                            Id = new Guid("7697bbd3-adfc-435d-a632-f18f32729668"),
                            ActualAmount = 5000m,
                            CategoryId = new Guid("30ace2f8-7ae2-4ecb-afb2-046865a905a6"),
                            PlannedAmount = 5000m,
                            SnapshotId = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            TransactionCount = 1
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("OverBudgetCategoryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("TotalBudgeted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblMonthlySnapshot_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblMonthlySnapshot", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a734a99-5ad3-4b05-a302-cbdc78ae96d3"),
                            Month = 5,
                            OverBudgetCategoryCount = 1,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SnapshotDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2650m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 42,
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("f51a306b-8962-4fb5-bd55-1d66373c85dd"),
                            Month = 6,
                            OverBudgetCategoryCount = 2,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            SnapshotDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalBudgeted = 3100m,
                            TotalExpenses = 2920m,
                            TotalIncome = 5000m,
                            TotalSavings = 500m,
                            TransactionCount = 38,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsPushEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("LargeTransactionThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<bool>("NotifyMonthlySummary")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetOverage")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnBudgetWarning")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnLargeTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnNewTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnSyncError")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWeeklySummary")
                        .HasColumnType("bit");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<TimeOnly>("QuietHoursEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("QuietHoursStart")
                        .HasColumnType("time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblNotificationPreference_Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblNotificationPreference_UserId");

                    b.ToTable("tblNotificationPreference", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ca2071e-9c1c-4861-ad8d-1c4c963cc3e9"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 100m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = true,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = true,
                            NotifyOnLargeTransaction = true,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        },
                        new
                        {
                            Id = new Guid("e09b69d6-a88e-4b46-a733-daa391126ece"),
                            AuthKey = "",
                            IsPushEnabled = false,
                            LargeTransactionThreshold = 200m,
                            LastUpdated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NotifyMonthlySummary = false,
                            NotifyOnBudgetOverage = true,
                            NotifyOnBudgetWarning = false,
                            NotifyOnLargeTransaction = false,
                            NotifyOnNewTransaction = true,
                            NotifyOnSyncError = true,
                            NotifyWeeklySummary = false,
                            P256dhKey = "",
                            PushEndpoint = "",
                            QuietHoursEnd = new TimeOnly(7, 0, 0),
                            QuietHoursStart = new TimeOnly(22, 0, 0),
                            UserId = new Guid("40b129a5-e9e9-4e77-8ec3-2553cb1245d7")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AccountSubtype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateLinked")
                        .HasColumnType("datetime");

                    b.Property<string>("InstitutionLogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("datetime");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPlaidAccount_Id");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPlaidAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Checking",
                            AccountSubtype = "checking",
                            AccountType = "depository",
                            AvailableBalance = 3150.00m,
                            CurrentBalance = 3200.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "1234",
                            PlaidAccountId = "demo_chk_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        },
                        new
                        {
                            Id = new Guid("42120fc4-7069-47d6-847b-15314ce50133"),
                            AccessTokenEncrypted = "DEMO_ENCRYPTED_TOKEN",
                            AccountName = "Savings",
                            AccountSubtype = "savings",
                            AccountType = "depository",
                            AvailableBalance = 8500.00m,
                            CurrentBalance = 8500.00m,
                            DateLinked = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionLogoUrl = "",
                            InstitutionName = "First National Bank",
                            IsActive = true,
                            IsoCurrencyCode = "USD",
                            LastSynced = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mask = "5678",
                            PlaidAccountId = "demo_sav_001",
                            PlaidItemId = "demo_item_001",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("PushEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("datetime");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblPushNotification_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPushNotification", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4df72c8d-1eca-47c8-b036-e4cae2aee49a"),
                            ActionUrl = "/budget",
                            Amount = 60m,
                            Body = "You've exceeded your Dining Out budget by $60.",
                            CategoryId = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 1,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Status = 1,
                            Title = "Dining Out over budget!",
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        },
                        new
                        {
                            Id = new Guid("c3171dae-f0c4-406d-8d97-d66f162865b9"),
                            ActionUrl = "/transactions",
                            Amount = 7m,
                            Body = "A $7.00 charge at Starbucks is pending review.",
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = false,
                            NotificationType = 0,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Status = 1,
                            Title = "New transaction: Starbucks",
                            TransactionId = new Guid("75d8a246-cb28-4c09-a303-08d2f53820e8"),
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        },
                        new
                        {
                            Id = new Guid("d1a25878-399a-4aa5-aa90-40c342ceba95"),
                            ActionUrl = "/budget",
                            Amount = 200m,
                            Body = "You've used 80% of your Transport budget.",
                            CategoryId = new Guid("79be1811-cf0f-428f-9f9c-31f0194c47ac"),
                            ErrorMessage = "",
                            Icon = "/icons/icon-192.png",
                            IsRead = true,
                            NotificationType = 2,
                            PushEndpoint = "",
                            ScheduledFor = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SentOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Status = 1,
                            Title = "Transport at 80%",
                            UserId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblSharedBudget_Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("UX_tblSharedBudget_InviteCode");

                    b.ToTable("tblSharedBudget", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shared household budget",
                            InviteCode = "XEESFJ",
                            IsActive = true,
                            MaxMembers = 10,
                            Name = "Demo Family Budget",
                            OwnerId = new Guid("926b898f-0450-4b4f-94ce-30c902b87205")
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("InsightType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblTrackingInsight_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblTrackingInsight", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33692c8a-e37e-4c3d-8ef7-5af0bd3a5aa5"),
                            Amount = 60m,
                            CategoryId = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            ChangePercent = 30.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 0,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You've spent $60 more than planned on dining this month.",
                            Month = 7,
                            Severity = 2,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Title = "Dining Out over budget",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("382603b3-0af2-4a37-a411-7fd227736395"),
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 7,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You have 2 transactions that haven't been assigned to a budget category.",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Title = "2 unassigned transactions",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("e71e9968-1e00-4a9f-9495-e3c12880e201"),
                            CategoryId = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            ChangePercent = -5.0,
                            GeneratedOn = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            InsightType = 1,
                            IsDismissed = false,
                            IsRead = false,
                            Message = "You're spending less on groceries than last month — great job!",
                            Month = 7,
                            Severity = 1,
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            Title = "Groceries on track",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("PlaidAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaidCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidSubcategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PlaidTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("tblBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblTransaction_Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaidAccountId");

                    b.HasIndex("PlaidTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_tblTransaction_PlaidTransactionId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("tblBudgetId");

                    b.ToTable("tblTransaction", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("622cc722-dd5a-40f3-acd7-74ccd66ea2fd"),
                            Amount = -1500m,
                            CategoryId = new Guid("ed9cb15e-29af-4e5a-bca3-e7a136517fb3"),
                            Description = "Monthly rent",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Rent Payment",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Payment",
                            PlaidSubcategory = "Rent",
                            PlaidTransactionId = "txn_001",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("769d240d-87d9-4a55-8194-d3d493b38b69"),
                            Amount = -127m,
                            CategoryId = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Whole Foods",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_002",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2e6b29c7-cf95-4ff4-9744-a14034271288"),
                            Amount = -14m,
                            CategoryId = new Guid("e15cf25b-e085-43b2-a35a-6f328f4a5b62"),
                            Description = "Lunch",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Chipotle",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Restaurants",
                            PlaidTransactionId = "txn_003",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c4642102-5a7a-4c92-8eb8-b41da17f1096"),
                            Amount = -62m,
                            CategoryId = new Guid("79be1811-cf0f-428f-9f9c-31f0194c47ac"),
                            Description = "Fuel",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Shell Gas Station",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Travel",
                            PlaidSubcategory = "Gas Stations",
                            PlaidTransactionId = "txn_004",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("baa6ecb4-38ab-4d83-987c-d8f5e8c35b65"),
                            Amount = -18m,
                            CategoryId = new Guid("7b0e162c-cd9f-4540-b9e1-9ff5a18e18ad"),
                            Description = "Streaming sub",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Netflix",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Service",
                            PlaidSubcategory = "Subscription",
                            PlaidTransactionId = "txn_005",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ccac5cd3-8edf-4714-b7b1-247d4b54523a"),
                            Amount = 5000m,
                            CategoryId = new Guid("30ace2f8-7ae2-4ecb-afb2-046865a905a6"),
                            Description = "Payroll",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = true,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Employer Direct Dep",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Payroll",
                            PlaidSubcategory = "Payroll",
                            PlaidTransactionId = "txn_006",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d6551933-7a67-41c8-8c14-0d02903f1a87"),
                            Amount = -89m,
                            CategoryId = new Guid("20b1aa0f-f1e5-4d8b-8ffb-1a4240f06fb3"),
                            Description = "Groceries",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Trader Joe's",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Supermarkets",
                            PlaidTransactionId = "txn_007",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cb4d659f-b2bd-4994-a227-cf7a434c1c42"),
                            Amount = -43m,
                            Description = "Online purchase",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Amazon",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Shopping",
                            PlaidSubcategory = "Online",
                            PlaidTransactionId = "txn_008",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("75d8a246-cb28-4c09-a303-08d2f53820e8"),
                            Amount = -7m,
                            Description = "Coffee",
                            IsExcluded = false,
                            IsPending = true,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "Starbucks",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Food and Drink",
                            PlaidSubcategory = "Coffee Shop",
                            PlaidTransactionId = "txn_009",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("16efd5a7-00df-4d63-a11c-bf190dd92989"),
                            Amount = -38m,
                            CategoryId = new Guid("94b0f9e0-87cd-4146-af66-add240f76988"),
                            Description = "Pharmacy",
                            IsExcluded = false,
                            IsPending = false,
                            IsReviewed = false,
                            IsoCurrencyCode = "USD",
                            MerchantName = "CVS Pharmacy",
                            Notes = "",
                            PlaidAccountId = new Guid("18616a35-8b4e-47e9-9701-9345757f800b"),
                            PlaidCategory = "Medical",
                            PlaidSubcategory = "Pharmacies",
                            PlaidTransactionId = "txn_010",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TransactionDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BudgetRole")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<Guid?>("SharedBudgetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("SharedBudgetId");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("926b898f-0450-4b4f-94ce-30c902b87205"),
                            BudgetRole = 0,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@emksave.com",
                            FirstName = "Alex",
                            LastName = "Demo",
                            Password = "Y7g4XITs1TDz/DlSKl9C+8XWPD8=",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TimeZone = "America/Chicago",
                            UserId = "owner"
                        },
                        new
                        {
                            Id = new Guid("40b129a5-e9e9-4e77-8ec3-2553cb1245d7"),
                            BudgetRole = 1,
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jamie@emksave.com",
                            FirstName = "Jamie",
                            LastName = "Smith",
                            Password = "1bqJSAdM2/NtF/Ycjz8HclbgT7M=",
                            SharedBudgetId = new Guid("2d11e4f4-3263-44ba-8d32-604272b4d779"),
                            TimeZone = "America/Chicago",
                            UserId = "member"
                        },
                        new
                        {
                            Id = new Guid("77503dc9-8293-48da-ba51-8d03b62ce5e7"),
                            CurrencyCode = "USD",
                            DateRegistered = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taylor@emksave.com",
                            FirstName = "Taylor",
                            LastName = "New",
                            Password = "PPz2fFi+bBSpHkNMZLKJkW7lB0Q=",
                            TimeZone = "America/Chicago",
                            UserId = "solo"
                        });
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Budgets")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudget_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblBudgetCategory_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCashFlowEntry", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("CashFlowEntries")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCashFlowEntry_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblCategorySummary", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblMonthlySnapshot", "Snapshot")
                        .WithMany("CategorySummaries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblCategorySummary_SnapshotId");

                    b.Navigation("Category");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("MonthlySnapshots")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblMonthlySnapshot_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblNotificationPreference", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("EMK.Save.PL.Entities.tblNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblNotificationPreference_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PlaidAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tblPlaidAccount_UserId");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPushNotification", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("PushNotifications")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblPushNotification_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("PushNotifications")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblTransaction", "Transaction")
                        .WithMany("PushNotifications")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblPushNotification_TransactionId");

                    b.HasOne("EMK.Save.PL.Entities.tblUser", "User")
                        .WithMany("PushNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblPushNotification_UserId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTrackingInsight", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTrackingInsight_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("TrackingInsights")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTrackingInsight_SharedBudgetId");

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblBudgetCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblTransaction_CategoryId");

                    b.HasOne("EMK.Save.PL.Entities.tblPlaidAccount", "PlaidAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("PlaidAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_PlaidAccountId");

                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany()
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_tblTransaction_SharedBudgetId");

                    b.HasOne("EMK.Save.PL.Entities.tblBudget", null)
                        .WithMany("Transactions")
                        .HasForeignKey("tblBudgetId");

                    b.Navigation("Category");

                    b.Navigation("PlaidAccount");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.HasOne("EMK.Save.PL.Entities.tblSharedBudget", "SharedBudget")
                        .WithMany("Members")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_tblUser_SharedBudgetId");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudget", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblBudgetCategory", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("CategorySummaries");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblMonthlySnapshot", b =>
                {
                    b.Navigation("CategorySummaries");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblPlaidAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblSharedBudget", b =>
                {
                    b.Navigation("BudgetCategories");

                    b.Navigation("Budgets");

                    b.Navigation("CashFlowEntries");

                    b.Navigation("Members");

                    b.Navigation("MonthlySnapshots");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");

                    b.Navigation("TrackingInsights");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblTransaction", b =>
                {
                    b.Navigation("PushNotifications");
                });

            modelBuilder.Entity("EMK.Save.PL.Entities.tblUser", b =>
                {
                    b.Navigation("NotificationPreference");

                    b.Navigation("PlaidAccounts");

                    b.Navigation("PushNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
